"""Inventory of dataset variants, generated FROM the Hydra configs.

A hand-maintained list of variants drifts the moment someone adds a config, so
``docs/variants.md`` is generated by this module instead of written by hand:

    python -m synapse_qc.variants           # print the tables
    python -m synapse_qc.variants --write   # regenerate docs/variants.md
    python -m synapse_qc.variants --check   # exit 1 if the doc is stale

``--check`` is the guard: run it after touching ``conf/`` and the doc can never
silently disagree with the configs it documents.

A variant is ``<cohort>__<preprocessing>`` -- the two Hydra config groups. Any
cohort can be combined with any preprocessing, so the config groups define the
*possible* variants and the outputs tree records which have actually been built.
"""
import argparse
import json
import os
import sys

from omegaconf import OmegaConf

from . import paths as qpaths

REPO = qpaths.REPO
CONF = os.path.join(REPO, "conf")
DOC = os.path.join(REPO, "docs", "variants.md")


def cohorts():
    """[(name, n_exp, n_ctrl, note)] from conf/cohort/*.yaml."""
    out = []
    for f in sorted(os.listdir(os.path.join(CONF, "cohort"))):
        if not f.endswith(".yaml"):
            continue
        c = OmegaConf.load(os.path.join(CONF, "cohort", f))
        exp, ctrl = list(c.get("exp") or []), list(c.get("ctrl") or [])
        note = ("auto-discovers every resolvable recording"
                if not exp and not ctrl else "")
        out.append((f, str(c.get("name")), len(exp), len(ctrl), note))
    return out


def preprocessings():
    """[(file, name, channel_strategy, inherits)] from conf/preprocessing/*.yaml."""
    out = []
    for f in sorted(os.listdir(os.path.join(CONF, "preprocessing"))):
        if not f.endswith(".yaml"):
            continue
        c = OmegaConf.load(os.path.join(CONF, "preprocessing", f))
        base = [d for d in (c.get("defaults") or []) if d != "_self_"]
        out.append((f, str(c.get("name")), str(c.get("channel_strategy")),
                    ", ".join(map(str, base)) or "—"))
    return out


def built(base=None):
    """[(product, dir, cohort, strategy, built, extra)] found in the outputs tree."""
    base = base or qpaths.resolve_base(warn=False)
    root = os.path.join(base, "outputs")
    found = []
    for product, rel in (("epochs", "epochs"),
                         ("multimodal-final", "multimodal/final")):
        d = os.path.join(root, rel)
        if not os.path.isdir(d):
            continue
        for name in sorted(os.listdir(d)):
            man = os.path.join(d, name, "manifest.json")
            if not os.path.isfile(man):
                continue
            j = json.load(open(man))
            found.append((product, f"{rel}/{name}", j.get("cohort", "?"),
                          j.get("channel_strategy", "?"),
                          str(j.get("built", ""))[:10], ""))
    mm = os.path.join(root, "multimodal")
    if os.path.isdir(mm):
        for name in sorted(n for n in os.listdir(mm) if n.startswith("paired")):
            man = os.path.join(mm, name, "manifest.json")
            if not os.path.isfile(man):
                continue
            j = json.load(open(man))
            n_sub = len([x for x in os.listdir(os.path.join(mm, name))
                         if os.path.isdir(os.path.join(mm, name, x))])
            found.append(("multimodal-paired", f"multimodal/{name}",
                          j.get("cohort", "?"), "— (detect-and-defer)",
                          str(j.get("built", ""))[:10], f"{n_sub} subjects"))
    return found


def render(include_built=True):
    L = ["# Dataset variants", "",
         "**Generated — do not edit by hand.** Regenerate with",
         "`python -m synapse_qc.variants --write`; `--check` fails if this file",
         "has drifted from `conf/`.", "",
         "A variant is `<cohort>__<preprocessing>` — the two Hydra config groups.",
         "Any cohort combines with any preprocessing, so the groups below define",
         "what is *possible*; the last table records what has actually been built.",
         "", "## Cohorts (`conf/cohort/`)", "",
         "| Config | `name` | EXP | CTRL | Total | Note |", "|---|---|---|---|---|---|"]
    for f, name, e, c, note in cohorts():
        tot = "auto" if not e and not c else str(e + c)
        L.append(f"| `{f}` | `{name}` | {e or '—'} | {c or '—'} | {tot} | {note} |")
    L += ["", "## Preprocessing (`conf/preprocessing/`)", "",
          "| Config | `name` | `channel_strategy` | Inherits |", "|---|---|---|---|"]
    for f, name, cs, base in preprocessings():
        L.append(f"| `{f}` | `{name}` | `{cs}` | {base} |")
    L += ["",
          "`channel_strategy` decides what happens to channels QC flagged bad:",
          "",
          "- **`drop`** — remove them (variable channel count per subject)",
          "- **`interpolate`** — spline-interpolate from neighbours (needs the spatial",
          "  montage; do **not** use on recordings with duplicated grids)",
          "- **`zero_mask`** — set to exactly 0.0, keep 16 channels + validity mask",
          "- **`keep_all`** — leave the raw values, keep 16 channels + validity mask",
          "",
          "`zero_mask` and `keep_all` differ *only* in the masked channels' contents;",
          "the mask is identical. Prefer `zero_mask` unless the consumer definitely",
          "reads `*_channel_mask.npy` — some bad channels here are railed at the ADC",
          "limit and would dominate any normalisation. See `docs/dataset_handoff.md`.",
          "", "## Usage", "",
          "```bash",
          "python -m pipelines.build_dataset    cohort=<c> preprocessing=<p>",
          "python -m pipelines.pair_video       cohort=<c>          # stage 1 (slow)",
          "python -m pipelines.finalize_dataset preprocessing=<p>   # stage 2 (fast)",
          "```", ""]
    if include_built:
        L += ["## Built (in the outputs tree)", "",
              "| Product | Path | Cohort | Strategy | Built | |",
              "|---|---|---|---|---|---|"]
        rows = built()
        if not rows:
            L.append("| _(none found — is `$SYNAPSE_DATA_BASE` set?)_ | | | | | |")
        for p, d, c, s, b, x in rows:
            L.append(f"| {p} | `{d}` | `{c}` | `{s}` | {b} | {x} |")
        L += ["",
              "Built variants are **not** regenerated by `--write`'s staleness check —",
              "only the config tables are, since the outputs tree changes as you build.",
              ""]
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--write", action="store_true", help="regenerate docs/variants.md")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the doc's config tables are stale")
    a = ap.parse_args()
    text = render()
    if a.check:
        if not os.path.exists(DOC):
            print(f"MISSING {DOC} — run --write"); sys.exit(1)
        cur = open(DOC).read()
        # compare only the config-derived part; built variants change freely
        marker = "## Built (in the outputs tree)"
        want, have = render(include_built=False), cur.split(marker)[0]
        if want.strip() != have.strip():
            print("STALE: docs/variants.md no longer matches conf/. Run --write.")
            sys.exit(1)
        print("docs/variants.md matches conf/")
        return
    if a.write:
        os.makedirs(os.path.dirname(DOC), exist_ok=True)
        open(DOC, "w").write(text + "\n")
        print(f"wrote {DOC}")
        return
    print(text)


if __name__ == "__main__":
    main()
